### ISSUE TITLE
data/cars.json is missing

### ISSUE THREAD

**Issue by awb99** [jsa-aerial/hanami#2]
data/cars.json is missing
:-)

**Comment by jsa-aerial** [comment]
It is in the jar, but I see I forgot to add to github - just, added - it's now in the repo. Since it is in the jar you could just pull it from there if you wanted to see it. Also, if you want to see all the VGL/VG data sets (from UWash IDL) have a look here: https://github.com/vega/vega-datasets/tree/gh-pages/data
